logging:
  level:
   root:
     info
management:
  endpoints:
    web:
      exposure:
        include:
          "*"
spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=user
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled:
        true
  jpa:
    defer-datasource-initialization: true
    show-sql: true

